%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.2

-ifndef(base_pb).
-define(base_pb, true).

-define(base_pb_gpb_version, "4.19.2").

-ifndef('C2SPACK_PB_H').
-define('C2SPACK_PB_H', true).
-record('C2SPack',
        {file = []              :: unicode:chardata() | undefined, % = 1, optional
         msg = []               :: unicode:chardata() | undefined, % = 2, optional
         pack = <<>>            :: iodata() | undefined % = 3, optional
        }).
-endif.

-ifndef('S2CPACK_PB_H').
-define('S2CPACK_PB_H', true).
-record('S2CPack',
        {file = []              :: unicode:chardata() | undefined, % = 1, optional
         msg = []               :: unicode:chardata() | undefined, % = 2, optional
         pack = <<>>            :: iodata() | undefined % = 3, optional
        }).
-endif.

-endif.
