%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.2

-ifndef(game_pb).
-define(game_pb, true).

-define(game_pb_gpb_version, "4.19.2").

-ifndef('DOING_PB_H').
-define('DOING_PB_H', true).
-record('Doing',
        {a = 0                  :: integer() | undefined % = 1, optional, 64 bits
        }).
-endif.

-endif.
