%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.2

-ifndef(login_pb).
-define(login_pb, true).

-define(login_pb_gpb_version, "4.19.2").

-ifndef('LOGINREQUEST_PB_H').
-define('LOGINREQUEST_PB_H', true).
-record('LoginRequest',
        {account = 0            :: integer() | undefined, % = 1, optional, 32 bits
         time = 0               :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-ifndef('LOGINRESPONSE_PB_H').
-define('LOGINRESPONSE_PB_H', true).
-record('LoginResponse',
        {result = false         :: boolean() | 0 | 1 | undefined, % = 1, optional
         reason = []            :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-endif.
